
server:
  #本服务中心端口
  port: 8761
eureka:
  client:
    service-url:
      #eureka server的默认端口是8761，如果不是默认端口，可以用以下方式变更
      defaultZone: http://localhost:${server.port}/eureka/
    # 由于该应用为注册中心，所以设置为false，代表不向注册中心注册自己
    register-with-eureka: false
    # 由于注册中心的职责就是维护服务实例，他并不需要去检索服务，所以也设置为false
    fetch-registry: false
  server:
    # 关闭自我保护
    enable-self-preservation: false
security:
  basic:
    #开启security验证
    enabled: true
  user:
    name: walnut
    password: 123456